#!/usr/bin/env python3
"""Write palette.json — the single colour lookup table for every Builder106 asset.

The hues all come from assets/hero-light.svg and assets/hero-dark.svg, which are
the source of truth for the profile's look. Three disciplines (HealthTech,
Mobile, Tooling) have no track in the hero, so their hues extend the same ramp
the hero tracks sit on, and Tooling reuses the hero's idle grey.

Lightness, though, is solved rather than copied. Each text colour is pushed away
from its backgrounds until it clears WCAG 2.2 AAA (7:1), and each meaningful
graphic — card borders, the accent bars — until it clears 1.4.11 (3:1). Hue and
saturation are held fixed while that happens, so the hero's palette survives the
adjustment. That is why a track carries two colours: `accent` for bars and
gradients, `text` for the label and index number set on top of them.

Run from the assets/ directory:
    python3 make_palette.py
"""

import json
from pathlib import Path

from a11y import AAA_TEXT, NON_TEXT, contrast, mix, solve

# --- hues, straight from the hero SVGs ---------------------------------------

CANVAS = {
    "light": {"canvas_from": "#ffffff", "canvas_to": "#f0f3f6", "surface": "#f6f8fa"},
    "dark": {"canvas_from": "#0b0f15", "canvas_to": "#161b22", "surface": "#161b22"},
}

# Decorative only: the dot grid and the giant ghosted "106". WCAG 1.4.11 exempts
# purely decorative graphics, so these keep the hero's values untouched.
DECOR = {
    "light": {"dots": "#d0d7de", "ghost": "#d0d7de"},
    "dark": {"dots": "#1f2630", "ghost": "#1c2530"},
}

NEUTRAL_SEED = {
    "light": {"fg": "#1f2328", "muted": "#656d76", "faded": "#8c959f", "accent": "#0284c7"},
    "dark": {"fg": "#e6edf3", "muted": "#7d8590", "faded": "#6e7681", "accent": "#38bdf8"},
}

# The hero's five cycling tracks, in hero order, then the three extensions.
TRACKS = {
    "W": {"label": "SWE", "light": "#0284c7", "dark": "#38bdf8"},
    "L": {"label": "AI/ML", "light": "#c2410c", "dark": "#fb923c"},
    "Y": {"label": "Cybersec", "light": "#b91c1c", "dark": "#f87171"},
    "A": {"label": "Analyst", "light": "#b45309", "dark": "#fbbf24"},
    "Q": {"label": "Quant", "light": "#15803d", "dark": "#4ade80"},
    "H": {"label": "HealthTech", "light": "#0e7490", "dark": "#22d3ee"},
    "M": {"label": "Mobile", "light": "#6d28d9", "dark": "#a78bfa"},
    "T": {"label": "Tooling", "light": "#656d76", "dark": "#7d8590"},
}

# How much accent bleeds into the surface for a discipline's card tint.
TINT_RATIO = 0.14

# `muted` is solved a little past the minimum so it stays visibly stronger than
# `faded`; both clear AAA.
MUTED_TARGET = 8.5

# Shields.io renders badge text in white, so badge fills are solved against it.
BADGE_TEXT = "#ffffff"

AWAY = {"light": "darken", "dark": "lighten"}


def build() -> dict:
    palette = {
        "_comment": (
            "Generated by make_palette.py. Hues mirror the hero SVGs; lightness is solved for "
            "WCAG 2.2 AAA text contrast (7:1) and 1.4.11 non-text contrast (3:1). Do not hand-edit."
        ),
        "neutral": {},
        "tracks": {},
    }

    for theme in ("light", "dark"):
        canvas = CANVAS[theme]
        seed = NEUTRAL_SEED[theme]
        direction = AWAY[theme]

        tints = {code: mix(track[theme], canvas["surface"], TINT_RATIO) for code, track in TRACKS.items()}
        # Every surface a neutral text colour can land on.
        text_backgrounds = list(canvas.values()) + list(tints.values())

        neutral = dict(canvas)
        neutral.update(DECOR[theme])
        neutral["fg"] = solve(seed["fg"], text_backgrounds, AAA_TEXT, direction)
        neutral["muted"] = solve(seed["muted"], text_backgrounds, MUTED_TARGET, direction)
        neutral["faded"] = solve(seed["faded"], text_backgrounds, AAA_TEXT, direction)
        # Hairlines and separator glyphs delineate content, so they take the
        # 3:1 non-text bar rather than the decorative exemption.
        neutral["rule"] = solve(seed["muted"], text_backgrounds, NON_TEXT, direction)
        neutral["border"] = neutral["rule"]
        # The hero's accent bar is a graphic; the accent used as text is not.
        neutral["accent"] = solve(seed["accent"], list(canvas.values()), NON_TEXT, direction)
        neutral["accent_text"] = solve(seed["accent"], text_backgrounds, AAA_TEXT, direction)
        palette["neutral"][theme] = neutral

        for code, track in TRACKS.items():
            entry = palette["tracks"].setdefault(code, {"label": track["label"]})
            tint = tints[code]
            on = [tint, *canvas.values()]
            entry[theme] = {
                "accent": solve(track[theme], on, NON_TEXT, direction),
                "text": solve(track[theme], on, AAA_TEXT, direction),
                "tint": tint,
            }
        # One badge colour per track — README badges render the same in both themes.
        for code, track in TRACKS.items():
            palette["tracks"][code]["badge"] = solve(track["light"], [BADGE_TEXT], AAA_TEXT, "darken")

    return palette


def report(palette: dict) -> None:
    for theme in ("light", "dark"):
        n = palette["neutral"][theme]
        worst = min(contrast(n["faded"], bg) for bg in (n["canvas_from"], n["canvas_to"], n["surface"]))
        print(f"{theme}: fg {n['fg']}  muted {n['muted']}  faded {n['faded']} (min {worst:.2f}:1)")
        for track in palette["tracks"].values():
            t = track[theme]
            print(
                f"  {track['label']:<11} accent {t['accent']}  text {t['text']} "
                f"({contrast(t['text'], t['tint']):.2f}:1 on tint)  badge {track['badge']}"
            )


if __name__ == "__main__":
    result = build()
    out = Path(__file__).parent / "palette.json"
    out.write_text(json.dumps(result, indent=2) + "\n")
    report(result)
    print(f"wrote {out}")
