#!/usr/bin/env python3
"""Write palette.json — the single colour lookup table for every Builder106 asset.

The hues all come from assets/hero-light.svg and assets/hero-dark.svg, which are
the source of truth for the profile's look. Three disciplines (HealthTech,
Mobile, Tooling) have no track in the hero, so their hues extend the same ramp
the hero tracks sit on, and Tooling reuses the hero's idle grey.

Lightness, though, is solved rather than copied. Each text colour is pushed away
from its backgrounds until it clears WCAG 2.2 AAA (7:1), and each meaningful
graphic — card borders, the accent bars — until it clears 1.4.11 (3:1). Hue and
saturation are held fixed while that happens, so the hero's palette survives the
adjustment. That is why a track carries two colours: `accent` for bars and
gradients, `text` for the label and index number set on top of them.

Run from the assets/ directory:
    python3 make_palette.py
"""

import colorsys
import json
from pathlib import Path

from a11y import AAA_LARGE_TEXT, AAA_TEXT, NON_TEXT, contrast, mix, solve, to_hex

# --- hues, straight from the hero SVGs ---------------------------------------

CANVAS = {
    "light": {"canvas_from": "#ffffff", "canvas_to": "#f0f3f6", "surface": "#f6f8fa"},
    "dark": {"canvas_from": "#0b0f15", "canvas_to": "#161b22", "surface": "#161b22"},
}

# Decorative only: the dot grid and the giant ghosted "106". WCAG 1.4.11 exempts
# purely decorative graphics, so these keep the hero's values untouched.
DECOR = {
    "light": {"dots": "#d0d7de", "ghost": "#d0d7de"},
    "dark": {"dots": "#1f2630", "ghost": "#1c2530"},
}

NEUTRAL_SEED = {
    "light": {"fg": "#1f2328", "muted": "#656d76", "faded": "#8c959f", "accent": "#0284c7"},
    "dark": {"fg": "#e6edf3", "muted": "#7d8590", "faded": "#6e7681", "accent": "#38bdf8"},
}

# Track hues, spaced around the colour wheel so that no two disciplines read as
# the same colour in the legend. The semantic anchors are kept — red for
# Cybersec, gold for Analyst, green for Quant, teal for HealthTech, blue for
# SWE — and the rest fill the gaps evenly. Saturation and lightness are fixed
# per theme; make_palette then solves each one for contrast.
TRACK_HUE = {
    "Y": ("Cybersec", 0),
    "A": ("Analyst", 45),
    "Q": ("Quant", 120),
    "H": ("HealthTech", 165),
    "W": ("SWE", 208),
    "M": ("Mobile", 252),
    "L": ("AI/ML", 305),
}

# Starting saturation/lightness per theme, before the contrast solve.
SEED_SL = {"light": (0.70, 0.34), "dark": (0.72, 0.68)}


def seed(hue: int, theme: str) -> str:
    saturation, lightness = SEED_SL[theme]
    return to_hex(colorsys.hls_to_rgb(hue / 360, lightness, saturation))


TRACKS = {
    code: {"label": label, "light": seed(hue, "light"), "dark": seed(hue, "dark")}
    for code, (label, hue) in TRACK_HUE.items()
}
TRACKS["T"] = {"label": "Tooling", "light": "#656d76", "dark": "#7d8590"}

# The table lays disciplines out in this order.
ORDER = ["Q", "L", "Y", "A", "W", "H", "M", "T"]
TRACKS = {code: TRACKS[code] for code in ORDER}

# How much accent bleeds into the surface for a discipline's card tint.
TINT_RATIO = 0.14

# `muted` is solved a little past the minimum so it stays visibly stronger than
# `faded`; both clear AAA.
MUTED_TARGET = 8.5

# WCAG counts 24px+, or 18.66px+ bold, as large text, where AAA asks for 4.5:1
# rather than 7:1. The hero sets its track labels at 32px semibold and the
# banner its tagline at 26px, so those get the `_large` variants below. Using
# the 7:1 colours there would be needlessly dark and would flatten the
# distinction between the five tracks, which is the whole point of the cycle.

# Shields.io renders badge text in white, so badge fills are solved against it.
BADGE_TEXT = "#ffffff"

AWAY = {"light": "darken", "dark": "lighten"}


def build() -> dict:
    palette = {
        "_comment": (
            "Generated by make_palette.py. Hues mirror the hero SVGs; lightness is solved for "
            "WCAG 2.2 AAA text contrast (7:1) and 1.4.11 non-text contrast (3:1). Do not hand-edit."
        ),
        "neutral": {},
        "tracks": {},
    }

    for theme in ("light", "dark"):
        canvas = CANVAS[theme]
        seed = NEUTRAL_SEED[theme]
        direction = AWAY[theme]

        tints = {code: mix(track[theme], canvas["surface"], TINT_RATIO) for code, track in TRACKS.items()}
        # Every surface a neutral text colour can land on.
        text_backgrounds = list(canvas.values()) + list(tints.values())

        neutral = dict(canvas)
        neutral.update(DECOR[theme])
        neutral["fg"] = solve(seed["fg"], text_backgrounds, AAA_TEXT, direction)
        neutral["muted"] = solve(seed["muted"], text_backgrounds, MUTED_TARGET, direction)
        neutral["faded"] = solve(seed["faded"], text_backgrounds, AAA_TEXT, direction)
        neutral["muted_large"] = solve(seed["muted"], text_backgrounds, AAA_LARGE_TEXT, direction)
        neutral["faded_large"] = solve(seed["faded"], text_backgrounds, AAA_LARGE_TEXT, direction)
        # Hairlines and separator glyphs delineate content, so they take the
        # 3:1 non-text bar rather than the decorative exemption.
        neutral["rule"] = solve(seed["muted"], text_backgrounds, NON_TEXT, direction)
        neutral["border"] = neutral["rule"]
        # The hero's accent bar is a graphic; the accent used as text is not.
        neutral["accent"] = solve(seed["accent"], list(canvas.values()), NON_TEXT, direction)
        neutral["accent_text"] = solve(seed["accent"], text_backgrounds, AAA_TEXT, direction)
        palette["neutral"][theme] = neutral

        for code, track in TRACKS.items():
            entry = palette["tracks"].setdefault(code, {"label": track["label"]})
            tint = tints[code]
            on = [tint, *canvas.values()]
            entry[theme] = {
                "accent": solve(track[theme], on, NON_TEXT, direction),
                "text": solve(track[theme], on, AAA_TEXT, direction),
                "text_large": solve(track[theme], on, AAA_LARGE_TEXT, direction),
                "tint": tint,
            }
        # One badge colour per track — README badges render the same in both themes.
        for code, track in TRACKS.items():
            palette["tracks"][code]["badge"] = solve(track["light"], [BADGE_TEXT], AAA_TEXT, "darken")

    return palette


def report(palette: dict) -> None:
    for theme in ("light", "dark"):
        n = palette["neutral"][theme]
        worst = min(contrast(n["faded"], bg) for bg in (n["canvas_from"], n["canvas_to"], n["surface"]))
        print(f"{theme}: fg {n['fg']}  muted {n['muted']}  faded {n['faded']} (min {worst:.2f}:1)")
        for track in palette["tracks"].values():
            t = track[theme]
            page = "#ffffff" if theme == "light" else "#0d1117"
            print(
                f"  {track['label']:<11} accent {t['accent']}  text {t['text']}  "
                f"large {t['text_large']} ({contrast(t['text_large'], page):.2f}:1 on page)"
            )


if __name__ == "__main__":
    result = build()
    out = Path(__file__).parent / "palette.json"
    out.write_text(json.dumps(result, indent=2) + "\n")
    report(result)
    print(f"wrote {out}")
